- hosts: _sonarqube
  # export ANSIBLE_HOST_KEY_CHECKING=False
  gather_facts: true
  become: true
  vars:
    ansible_ssh_private_key_file: "/var/lib/jenkins/workspace/aws-infra-pipeline/.ssh/sonarqube-key.pem"
  
  tasks:

    - name: Wait for SSH to be available
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: 300   # increase timeout if needed
        state: started
  # main file
  roles:
    - sonarqube
