- hosts: _sonarqube
  # export ANSIBLE_HOST_KEY_CHECKING=False
  gather_facts: true
  become: true
  vars:
    ansible_ssh_private_key_file: "/var/lib/jenkins/workspace/aws-infra-pipeline/.ssh/sonarqube-key.pem"
  # main file
  roles:
    - sonarqube
